# Generated by Django 2.0.3 on 2018-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('img_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('post_time', models.DateTimeField()),
                ('pre_content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'nba_news',
            },
        ),
    ]
